### ISSUE TITLE
Add ability to change character count for toggle

### ISSUE THREAD

**Issue by robinrosenstock** [jrappen/sublime-distractionless#1]
I'm missing the functionality, when the plugin enters into distraction free mode.
And I don't know how many keystrokes are needed or in which time it enters distraction free mode.
There should be some more settings in general, I suggest.

### Environment

```text
distractionless:

    version: v1.0.11
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: Build 3126
    platform: Windows
    architecture: x64
```

**Comment by jrappen** [comment]
Currently `distractionless` toggles after entering 10 characters:

https://github.com/jrappen/sublime-distractionless/blob/11e248c7247bee1ba70f217979e4d55bf33b6643/src/distractionless.py#L31

I'll add an optional setting if that works for you.
